// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrationen laufen ueber den privilegierten DB-Owner (DDL-Rechte,
  // RLS-Bypass fuers Seeding) - nicht ueber den eingeschraenkten Laufzeit-
  // Benutzer aus DATABASE_URL (siehe src/lib/prisma.ts).
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"],
  },
});
